// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/tab-bar/tabbar copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabbar: typeof import('./src/components/tab-bar/tabbar.vue')['default']
    Tabbar_01: typeof import('./src/components/tab-bar/tabbar_01.vue')['default']
    Tabbar_02: typeof import('./src/components/tab-bar/tabbar_02.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanRate: typeof import('vant/es')['Rate']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
